"""全局常量定义模块，包含超时、限流、上传限制、WebSocket 等配置常量。"""

API_PREFIX = "/api"

# Timeout defaults (seconds)
EXTERNAL_CONNECT_TIMEOUT = 2.0
EXTERNAL_READ_TIMEOUT = 30.0
EXTERNAL_TOTAL_TIMEOUT = 35.0
LLM_VISION_TIMEOUT = 50.0
LLM_TEXT_TIMEOUT = 30.0
LLM_CHAT_STREAM_CHUNK_TIMEOUT = 30.0   # 單一 chunk 間最大等待秒數
LLM_CHAT_STREAM_TOTAL_TIMEOUT = 120.0  # 串流整體最大秒數
WS_OPENAI_CONNECT_TIMEOUT = 10.0

# Rate limiting
DEFAULT_RATE_LIMIT_PER_MINUTE = 60

# Upload limits
MAX_IMAGE_SIZE_MB = 10
MAX_SCENE_DESCRIPTION_LENGTH = 2000
MAX_CHAT_TEXT_LENGTH = 5000

# Supported image formats (base64 prefix detection)
SUPPORTED_IMAGE_PREFIXES = ("data:image/jpeg", "data:image/png", "data:image/webp")

# WebSocket
WS_HEARTBEAT_INTERVAL = 20
WS_HEARTBEAT_TIMEOUT = 10

# Voice coach session
VOICE_COACH_SESSION_TTL_SECONDS = 1800  # 30 minutes

# Match 模組
MAX_MATCH_NAME_LENGTH = 128
MAX_CONTEXT_TAG_LENGTH = 128

# Persona 模組
MAX_SANDBOX_TEXT_LENGTH = 500

# Love Coach 模組
MAX_LOVE_COACH_MESSAGE_LENGTH = 2000
